name: 'GH-Issues-LtT'
description: 'Extracts lists from a GitHub Issue and Transforms them to Tasks'
inputs:
  user:
    description: 'Issue Owner'
    required: true
  repo:
    description: 'Repository To Monitor'
    required: true
  issueNumber:
    description: 'Created / Edited Issue Number'
    required: true
  aggregateIssueLabel:
    description: 'Label to Mark the Aggregate Issue'
    required: true
    default: 'gh-issues-ltt'
runs:
  using: 'node12'
  main: 'dist/index.js'