name: 'Action Items Sync'
description: 'Extract action items from multiple issues and aggregate them into 1'
inputs:
  owner:
    description: 'Repository Owner (User or Organization)'
    required: true

  repo:
    description: 'Repository To Monitor'
    required: true

  issueNumber:
    description: 'Created / Edited Issue Number'
    required: true

  aggregateIssueLabel:
    description: 'Label to Mark the Aggregate Issue'
    required: true
    default: 'gh-issues-ltt'
runs:
  using: 'node12'
  main: 'dist/index.js'