name: Synchronize Action Items
on:
  issues:
    types: [opened, edited]


jobs:
  fetchIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: link-/gh-issues-ltt@v0.2-alpha
        id: sync_action_items
        with:
          user: "Link-"
          repo: "gh-issues-ltt"
          issueNumber: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
