name: Synchronize Action Items
on:
  issues:
    types: [opened, edited]


jobs:
  Sync-Action-Items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Sync Ation Items"
        id: sync_action_items
        uses: ./
        with:
          user: "Link-"
          repo: "gh-issues-ltt"
          issuenumber: "${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}